//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentWorldTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Halls = new HashSet<Hall>();
            this.Users = new HashSet<User>();
        }
    
        public int B_ID { get; set; }
        public string B_Name { get; set; }
        public string B_Address { get; set; }
        public string B_DetailInfo { get; set; }
        public int O_ID { get; set; }
        public string B_Picture { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Hall> Halls { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
