//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentWorldTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        public Hall()
        {
            this.Schedules = new HashSet<Schedule>();
            this.Seats = new HashSet<Seat>();
        }
    
        public int H_ID { get; set; }
        public string H_Name { get; set; }
        public int H_SeatNumbers { get; set; }
        public int B_ID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
