//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentWorldTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Or_ID { get; set; }
        public System.DateTime O_DateTime { get; set; }
        public string Or_Status { get; set; }
        public string Or_UserName { get; set; }
        public int Or_UserPhone { get; set; }
        public string Or_UserEmail { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
