//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentWorldTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrD_ID { get; set; }
        public int OS_ID { get; set; }
        public int P_ID { get; set; }
        public int Or_ID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Performance Performance { get; set; }
        public virtual OrderSeat OrderSeat { get; set; }
    }
}
