//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentWorldTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Branches = new HashSet<Branch>();
        }
    
        public int O_ID { get; set; }
        public string O_Name { get; set; }
        public string O_Address { get; set; }
        public string O_Web { get; set; }
        public string O_DetailInfo { get; set; }
        public string O_Picture { get; set; }
    
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
