//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentWorldTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public Performance()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public string P_Trailer { get; set; }
        public string P_Poster { get; set; }
        public string P_Author { get; set; }
        public string P_Genre { get; set; }
        public string P_Actors { get; set; }
        public int P_Hour { get; set; }
        public System.DateTime P_StartDay { get; set; }
        public string P_DetailInfo { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
