//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentWorldTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Sc_ID { get; set; }
        public int Sc_Price { get; set; }
        public int Sc_Day { get; set; }
        public int H_ID { get; set; }
        public int P_ID { get; set; }
        public System.TimeSpan Sc_StartHour { get; set; }
        public System.DateTime Sc_StartDate { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual Performance Performance { get; set; }
    }
}
