//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentWorldTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Se_ID { get; set; }
        public int Se_X { get; set; }
        public int Se_Y { get; set; }
        public int H_ID { get; set; }
        public int OS_ID { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual OrderSeat OrderSeat { get; set; }
    }
}
